apache_virtual_hosts:
  - dns: devops.com
  - dns: devsec.com
  - dns: devsecops.com

wp_version: 5.0.3
wp_db_host: s3.infra
wp_mysql_db: 'wordpress_db'
wp_mysql_user: 'wordpress_usr'
wp_mysql_password: 'wordpress_usr123'
 
wordpress_user: wordpress_usr
wordpress_password: 'wordpress_usr123'
wp_webserver: apache

wp_sitename: devops.com
wp_install_dir: /var/www/devops.com

#    wp_sitename: "{{ item.dns }}"
    wp_admin_email: 'your@email.com'
#    wp_install_dir: "/var/www/{{ item.dns }}"
    
    #  with_items: "{{ apache_virtual_hosts }}"



