wordpress_installs:
  - name: devops
    dbname: devops_db
    dbuser: devops_user
    dbpass: "devops_user123"
    dbhost: s3.infra
    path: "/var/www/devops.com"
    title: devops
    admin_name: admin
    admin_email: "admin@devops.com"
    admin_password: admin
    url: http://devops.com
    themes:
      - name: twentytwelve
        activate: true
    plugins: []
    users: {}
    options: []
    queries: []      
  - name: devsec
    dbname: devsec_db
    dbuser: devsec_user
    dbpass: "devsec_user123"
    dbhost: s3.infra
    path: "/var/www/devsec.com"
    title: devsec
    admin_name: admin
    admin_email: "admin@devsec.com"
    admin_password: admin
    url: http://devsec.com
    themes:
      - name: twentytwelve
        activate: true  
    plugins: []
    users: {}
    options: []
    queries: []        
  - name: devsecops
    dbname: devsecops_db
    dbuser: devsecops_user
    dbpass: "devsecops_user123"
    dbhost: s3.infra
    path: "/var/www/devsecops.com"
    title: devsecops
    admin_name: admin
    admin_email: "admin@devsecops.com"
    admin_password: admin
    url: http://devsecops.com
    themes:
      - name: twentytwelve
        activate: true
    plugins: []
    users: {}
    options: []
    queries: []        
